/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_learning_path.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk_rev2.h"

// Button A
#define BUTTON_A AVNET_MT3620_SK_USER_BUTTON_A

// Button B
#define BUTTON_B AVNET_MT3620_SK_USER_BUTTON_B

// Azure Connected
#define AZURE_CONNECTED_LED AVNET_MT3620_SK_APP_STATUS_LED_YELLOW

// Red LED
#define LED_RED AVNET_MT3620_SK_USER_LED_RED

// Green LED
#define LED_GREEN AVNET_MT3620_SK_USER_LED_GREEN

// Blue LED
#define LED_BLUE AVNET_MT3620_SK_USER_LED_BLUE

// Altair panel - switch load
#define SWITCHES_LOAD AVNET_MT3620_SK_GPIO42

// Altair panel - switch load
#define SWITCHES_CHIP_SELECT AVNET_MT3620_SK_GPIO2

// Altair panel - LED reset
#define LED_MASTER_RESET AVNET_MT3620_SK_GPIO0

// Altair panel - LED Store
#define LED_STORE AVNET_MT3620_SK_GPIO5

// Altair panel - LED Output enbale
#define LED_OUTPUT_ENABLE AVNET_MT3620_SK_GPIO1

// AVNET Start Kit Definition
#define ISU2 AVNET_MT3620_SK_ISU2_I2C

