/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_learning_path.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// MT3620 RDB: Button A
#define BUTTON_A MT3620_RDB_BUTTON_A

// MT3620 RDB: Button B
#define BUTTON_B MT3620_RDB_BUTTON_B

// MQTT Connected
#define MQTT_CONNECTED_LED MT3620_RDB_LED1_GREEN

// Azure Connected
#define AZURE_CONNECTED_LED MT3620_RDB_NETWORKING_LED_RED

// ISU0 UART is exposed on header 2, pin 1 (RX), pin 3 (TX), pin 5 (CTS), pin 7 (RTS)
#define UART0 MT3620_RDB_HEADER2_ISU0_UART

// MT3620 RDB: LED 1
#define LED_RED MT3620_RDB_LED4_RED

// MT3620 RDB: LED 1
#define LED_GREEN MT3620_RDB_LED4_GREEN

// MT3620 RDB: LED 1
#define LED_BLUE MT3620_RDB_LED4_BLUE

// Mapped to ISU 0 as not used on Seeed RDB
#define ISU2 MT3620_RDB_HEADER2_ISU0_I2C

// Altair panel - switch load
#define SWITCHES_LOAD MT3620_RDB_HEADER4_PIN14_GPIO

// Altair panel - switch load
#define SWITCHES_CHIP_SELECT MT3620_RDB_HEADER4_PIN12_GPIO

// Altair panel - LED reset
#define LED_MASTER_RESET MT3620_RDB_HEADER4_PIN10_GPIO

// Altair panel - LED Store
#define LED_STORE MT3620_RDB_HEADER4_PIN8_GPIO

// Altair panel - LED Output enbale
#define LED_OUTPUT_ENABLE MT3620_RDB_HEADER4_PIN6_GPIO

// Altair panel - SD Card select
#define SD_CARD_CHIP_SELECT MT3620_RDB_HEADER3_PIN12_GPIO

